name: Build Test .NET
description: Build Test .NET
inputs:
  project_file_path:
    description: Build Test Project File Path
    required: true
  build_configuration:
    description: Build configuration (e.g., Debug, Release)
    required: true
  dotnet_version:
    description: .NET version to use
    required: true
runs:
  using: "composite"
  steps:
    # Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Build Test on Linux
      if: runner.os == 'Linux'
      run: |
        chmod +x ./.scripts/build-test/dotnet.sh
        ./.scripts/build-test/dotnet.sh "$PROJECT_FILE_PATH" "$BUILD_CONFIGURATION"
        chmod -x ./.scripts/build-test/dotnet.sh
      env: 
        PROJECT_FILE_PATH: "${{ inputs.project_file_path }}"
        BUILD_CONFIGURATION: "${{ inputs.build_configuration }}"
      shell: bash

    - name: Build Test on Windows
      if: runner.os == 'Windows'
      run: ./.scripts/build-test/dotnet.ps1 -ProjectFilePath "$PROJECT_FILE_PATH" -BuildConfiguration "$BUILD_CONFIGURATION"
      env: 
        PROJECT_FILE_PATH: "${{ inputs.project_file_path }}"
        BUILD_CONFIGURATION: "${{ inputs.build_configuration }}"
      shell: pwsh
