name: "Create Tag"
description: "Create and debug a Git tag."

outputs:
  tag:
    description: "Generated Git tag"

runs:
  using: "composite"
  steps:

    - name: Add Execute Permission for Scripts
      run: chmod +x ${{ github.action_path }}/scripts/*.sh
      shell: bash

    - name: Run Git Create Tag Script
      run: ${{ github.action_path }}/scripts/create-tag.sh
      shell: bash

    - name: Create and Fetch Git Tag
      id: get_tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "Generated TAG: $TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "::set-output name=tag::$TAG"
      shell: bash



    - name: Remove Execute Permission for Scripts
      run: chmod -x ${{ github.action_path }}/scripts/*.sh
      shell: bash