name: "Create Tag"
description: "Create and debug a Git tag."
inputs:
  tag_script_path:
    description: "Path to the tag creation script"
    required: true
  debug_tags:
    description: "Enable debug information for tags"
    required: false
    default: "true"

outputs:
  tag:
    description: "Generated Git tag"

runs:
  using: "composite"
  steps:


    - name: Script Setting
      run: chmod +x ${{ inputs.tag_script_path }}
      shell: bash

    - name: Create Tag
      run: ${{ inputs.tag_script_path }}
      shell: bash

    - name: Create and Fetch Git Tag
      id: get_tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "Generated TAG: $TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "::set-output name=tag::$TAG"
      shell: bash

    - name: Debug Git Tag
      if: ${{ inputs.debug_tags == 'true' }}
      run: |
        echo "Available Tags:"
        git tag
      shell: bash