name: Env Check
description: Validate and display Git environment variables and provided file paths
inputs:
  config:
    description: JSON-encoded configuration for the action
    required: true
    default: "{}"

runs:
  using: "composite"
  steps:
    - name: Set SCRIPTS_DIR from Environment
      run: echo "SCRIPTS_DIR=${{ github.action_path }}/scripts" >> $GITHUB_ENV
      shell: bash

    - name: Parse JSON Config
      run: |
        cat <<EOF >> $GITHUB_ENV
        CONFIG=${{ inputs.config }}
        EOF
      shell: bash

    - name: Process Config with Bash
      run: |
        # Load CONFIG from $GITHUB_ENV
        CONFIG="${CONFIG:-{}}"

        # Debug: Print the received JSON
        echo "Received config: $CONFIG"

        # Parse JSON using jq
        solution_file=$(echo "$CONFIG" | jq -r '.solution_file')
        dll_file=$(echo "$CONFIG" | jq -r '.dll_file')
        tester_file=$(echo "$CONFIG" | jq -r '.tester_file')

        # Display parsed values
        echo "Solution File: $solution_file"
        echo "DLL File: $dll_file"
        echo "Tester File: $tester_file"
      shell: bash

    - name: Clean Up Environment Variables
      run: |
        sed -i '/^CONFIG=/d' $GITHUB_ENV
      shell: bash
