name: Env Check
description: Validate and display Git environment variables and provided file paths
inputs:
  config:
    description: JSON-encoded configuration for the action
    required: true
    default: "{}"

runs:
  using: composite
  steps:
    - name: Process Dynamic JSON Config
      run: |
        CONFIG="${{ inputs.config }}"
        echo "Processing dynamic JSON configuration:"
        echo "$CONFIG" | jq -c 'to_entries[] | "\(.key): \(.value)"'
      shell: bash
