name: "Check Tags"
description: "Browse the highest version tag and the entire list."

inputs:
  prefix:
    description: "Prefix to filter tags (e.g., 'v' or 'tag')"
    required: false
    default: "v"

runs:
  using: "composite"
  steps:

    - name: Add Execute Permission for Scripts
      run: |
        # Add Execute Permission for Scripts
        chmod +x ./.scripts/check/all_tag_version.sh
        chmod +x ./.scripts/check/latest_tag_version.sh
      shell: bash

    - name: List All Tags
      run: ${{github.action_path}}/scripts/all-list.sh ${{ inputs.prefix }}
      shell: bash

    - name: Highest Git Version
      run: ${{github.action_path}}/scripts/top-version.sh ${{ inputs.prefix }}
      shell: bash

    - name: List All Tags
      run: ${{github.action_path}}/scripts/all-list.sh ${{ inputs.prefix }}
      shell: bash

    - name: Remove Execute Permission for Scripts
      run: |
        # Remove Execute Permission for Scripts
        chmod -x ./.scripts/check/all_tag_version.sh
        chmod -x ./.scripts/check/latest_tag_version.sh
      shell: bash