name: Git Info
description: Retrieve and handle Git information based on event type
inputs:
  event_name:
    description: The GitHub event name (e.g., push, pull_request)
    required: true
  ref:
    description: The GitHub ref (e.g., refs/heads/main)
    required: false
  head_ref:
    description: The head ref (source branch for PRs)
    required: false
  base_ref:
    description: The base ref (target branch for PRs)
    required: false

runs:
  using: "composite"
  steps:
    - name: Set Script Directory
      id: set_script_dir
      run: echo "SCRIPTS_DIR=$GITHUB_WORKSPACE/.github/scripts" >> $GITHUB_ENV
      shell: bash

    - name: Add Execute Permission for Scripts
      run: chmod +x $SCRIPTS_DIR/*.sh
      shell: bash

    - name: Run Git Info Script
      run: $SCRIPTS_DIR/git-info.sh $SCRIPTS_DIR "${{ inputs.event_name }}" "${{ inputs.ref }}" "${{ inputs.head_ref }}" "${{ inputs.base_ref }}"
      shell: bash

    - name: Remove Execute Permission for Scripts
      run: chmod -x $SCRIPTS_DIR/*.sh
      shell: bash
