name: Git Info
description: Retrieve and handle Git information based on event type
inputs:
  event_name:
    description: The GitHub event name (e.g., push, pull_request)
    required: true
  ref:
    description: The GitHub ref (e.g., refs/heads/main)
    required: false
  head_ref:
    description: The head ref (source branch for PRs)
    required: false
  base_ref:
    description: The base ref (target branch for PRs)
    required: false

env:
  GIT_INFO_FILE: "${{ github.action_path }}/scripts/git-info.sh"

runs:
  using: "composite"
  steps:

    - name: Add Execute Permission for Script
      run: chmod +x "${{ env.GIT_INFO_FILE }}"
      shell: bash

    - name: Run Git Info Script
      run: "${{ env.GIT_INFO_FILE }}" "${{ inputs.event_name }}" "${{ inputs.ref }}" "${{ inputs.head_ref }}" "${{ inputs.base_ref }}"
      shell: bash

    - name: Remove Execute Permission for Script
      run: chmod -x "${{ env.GIT_INFO_FILE }}"
      shell: bash