name: "Auto Project Apply"
description: "Automate project updates, including version changes and branch protection management."

inputs:
  dll_file:
    description: "The DLL file path"
    required: true
  tester_file:
    description: "The tester project file path (optional)"
    required: false
  version:
    description: "The version to apply to the project files"
    required: true
  commit_hash:
    description: "The commit hash to apply to the project files"
    required: true
  user_name:
    description: "The Git username"
    required: false
  user_email:
    description: "The Git email"
    required: false
  github_user:
    description: "The GitHub username or organization"
    required: true
  github_repo:
    description: "The repository name"
    required: true
  branch_name:
    description: "The branch name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Add Execute Permission
      run: chmod +x ${{ github.action_path }}/scripts/*.sh
      shell: bash

    - name: Edit Project Version
      run: ${{ github.action_path }}/scripts/edit-project-version.sh ${{ inputs.version }} ${{ inputs.commit_hash }} ${{ inputs.dll_file }} ${{ inputs.tester_file }}
      shell: bash

    - name: Disable Branch Protection
      run: ${{ github.action_path }}/scripts/disable-enable-branch-protection.sh disable ${{ inputs.github_user }} ${{ inputs.github_repo }} ${{ inputs.branch_name }}
      shell: bash
      env:
        GH_PAT: ${{ env.GH_PAT }}

    - name: Overwrite Commit
      run: ${{ github.action_path }}/scripts/overwrite-commit.sh ${{ inputs.commit_hash }} ${{ inputs.dll_file }} ${{ inputs.tester_file }} ${{ inputs.user_name }} ${{ inputs.user_email }}
      shell: bash

    - name: Restore Branch Protection
      run: ${{ github.action_path }}/scripts/disable-enable-branch-protection.sh enable ${{ inputs.github_user }} ${{ inputs.github_repo }} ${{ inputs.branch_name }}
      shell: bash
      env:
        GH_PAT: ${{ env.GH_PAT }}

    - name: Remove Execute Permission
      run: chmod -x ${{ github.action_path }}/scripts/*.sh
      shell: bash
