name: Info
description: ""
inputs:
  # solution & project
  solution_file_path:
    description: ""
    required: true
  dll_project_file_path:
    description: ""
    required: true
  build_directory_path:
    description: ""
    required: false
    default: "N/A"
  tester_project_file_path:
    description: ""
    required: false
    default: "N/A"
  tester_executable_file_name:
    description: ""
    required: false
    default: "N/A"

  # deploy
  result_zip_name:
    description: ""
    required: true
  tag_prefix:
    description: ""
    required: true

  # git
  git_event_name:
    description: ""
    required: true
  git_ref:
    description: ""
    required: false
    default: "N/A"
  head_ref:
    description: ""
    required: false
    default: "N/A"
  base_ref:
    description: ""
    required: false
    default: "N/A"

runs:
  using: "composite"
  steps:
    - name: Add Execute Permission for Scripts
      run: |
        chmod +x ./.scripts/check/*.sh
      shell: bash

    - name: Check Solution & Project Values
      env:
        list: |
          {
            "Solution File Path": "SimpleFileIO.sln",
            "Dll File Path": "SimpleFileIO/SimpleFileIO.csproj",
            "Build Directory Path": "./build",
            "Tester File Path": "SimpleFileIO_Tester/SimpleFileIO_Tester.csproj",
            "Tester Executable File Name": "SimpleFileIO_Tester"
          }
      run: |
        echo "JSON Configuration: $list"
        ./.scripts/check/values.sh ${{ env.list }} solution_project_value.result
      shell: bash

    - name: Check Deploy Values
      run: ./.scripts/check/values.sh "${{ env.list }}" "deploy_value.result"
      env: 
        list: |
          {
            "Result Zip Name": "${{ inputs.result_zip_name }}",
            "Tag Prefix": "${{ inputs.tag_prefix }}"
          }
      shell: bash

    - name: Check Git Values
      run: ./.scripts/check/values.sh "${{ env.list }}" "git_value.result"
      env: 
        list: |
          {
            "Event": "${{ inputs.git_event_name }}",
            "Ref": "${{ inputs.git_ref }}",
            "Head Ref": "${{ inputs.head_ref }}",
            "Base Ref": "${{ inputs.base_ref }}"
          }
      shell: bash

    - name: Output
      run: |
        echo ::group:: Solution & Project
        cat solution_project_value.result
        echo ::endgroup::
        echo ::group:: Deploy
        cat deploy_value.result
        echo ::endgroup::
        echo ::group:: Git
        cat git_value.result
        echo ::endgroup::
      shell: bash

    - name: Remove Execute Permission for Scripts
      run: |
        chmod -x ./.scripts/check/*.sh
      shell: bash
