//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFileIO.Resources.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleFileIO.Resources.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Exception occurred while adding log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string add_work {
            get {
                return ResourceManager.GetString("add_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   111과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string clear_work {
            get {
                return ResourceManager.GetString("clear_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following exception occurred during route properties:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string path_property_work {
            get {
                return ResourceManager.GetString("path_property_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already writing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string write_already_writing {
            get {
                return ResourceManager.GetString("write_already_writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is 0 after deep copy when Buffer is non-zero과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string write_copy_invaild {
            get {
                return ResourceManager.GetString("write_copy_invaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deep copy of buffer, exception occurred during initialization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string write_deep_copying {
            get {
                return ResourceManager.GetString("write_deep_copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write Task exception occurs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string write_task_cancellation_token {
            get {
                return ResourceManager.GetString("write_task_cancellation_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Root directory is Null과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string write_task_root_directory_not_found {
            get {
                return ResourceManager.GetString("write_task_root_directory_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception occurred during internal operation of Write Task과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string write_task_work {
            get {
                return ResourceManager.GetString("write_task_work", resourceCulture);
            }
        }
    }
}
