name: Build Test .NET
description: Build Test .NET
inputs:
  project_file_path:
    description: Build Test Project File Path
    required: true
  build_configuration:
    description: Build configuration (e.g., Debug, Release)
    required: true
  dotnet_version:
    description: .NET version to use
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    # Output Result Log 
    # ./${{ runner.os }}/${{ inputs.build_configuration }}.result
    - name: Build Test on Linux
      if: runner.os == 'Linux'
      run: |
        chmod +x ./.scripts/build-validation/dotnet.sh
        ./.scripts/build-validation/dotnet.sh "${{ inputs.project_file_path }}" "${{ inputs.build_configuration }}" "./${{ runner.os }}/${{ inputs.build_configuration }}.result"
        cat ./${{ runner.os }}/${{ inputs.build_configuration }}.result
        chmod -x ./.scripts/build-validation/dotnet.sh
      shell: bash

    # Output Result Log 
    # ./${{ runner.os }}/${{ inputs.build_configuration }}.result
    - name: Build Test on Windows
      if: runner.os == 'Windows'
      run: |
        ./.scripts/build-validation/dotnet.ps1 "${{ inputs.project_file_path }}" "${{ inputs.build_configuration }}" "./${{ runner.os }}/${{ inputs.build_configuration }}.result"
        Get-Content ./${{ runner.os }}/${{ inputs.build_configuration }}.result
        Get-ChildItem -Recurse | ForEach-Object { $_.FullName }
      shell: pwsh

