name: Build Test .NET
description: >
  Build Test .NET
inputs:
  project_file_path:
    description: Build Test Project File Path
    required: true
  build_configuration:
    description: Build configuration (e.g., Debug, Release)
    required: true
  dotnet_version:
    description: .NET version to use
    required: true
outputs:
  result:
    description: build result
    value: ${{ steps.output.outputs.result }}
env:
  TEMP_RESULT_PATH: ./result.result
runs:
  using: "composite"
  steps:
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Build Test on Linux
      if: runner.os == 'Linux'
      run: |
        # Build Test on Linux
        chmod +x ./.scripts/build_validation/dotnet.sh
        ./.scripts/build_validation/dotnet.sh "${{ inputs.project_file_path }}" "${{ inputs.build_configuration }}" "${{ TEMP_RESULT_PATH }}"
        chmod -x ./.scripts/build_validation/dotnet.sh
      shell: bash

    - name: Build Test on Windows
      if: runner.os == 'Windows'
      run: |
        # Build Test on Windows
        ./.scripts/build_validation/dotnet.ps1 "${{ inputs.project_file_path }}" "${{ inputs.build_configuration }}" "${{ TEMP_RESULT_PATH }}"
      shell: pwsh

    - name: Output
      id: output
      run: |
        # Output

        # Multi Line
        multi_line_output=$(cat ${{ TEMP_RESULT_PATH }})
        echo "result<<EOF" >> $GITHUB_OUTPUT
        echo "$multi_line_output" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Remove Temp Result
        rm -f $TEMP_RESULT_PATH
      shell: bash