name: "Create Tag"
description: "Create and push a new Git tag based on the highest version tag."

inputs:
  prefix:
    description: "Prefix for tag filtering"
    required: false
    default: "v"

runs:
  using: "composite"
  steps:
    - name: Add Execute Permission for Scripts
      run: |
        # Add Execute Permission for Scripts
        chmod +x ./.scripts/check/all_tag_version.sh
        chmod +x ./.scripts/check/latest_tag_version.sh
      shell: bash

    - name: Check Before Tag State
      run: |
        # Check Before Tag State
        latest_tag=$(./.scripts/check/latest_tag_version "$PREFIX")
        echo -e "Latest Tag: $latest_tag"
        echo -e ""
      env:
        PREFIX: ${{ inputs.prefix }}
        
      shell: bash

    - name: Generate and Push New Tag
      run: |
        # Generate and Push New Tag
      shell: bash

    - name: Check After Tag State
      run: |
        # Check After Tag State
      shell: bash

    - name: Remove Execute Permission for Scripts
      run: |
        # Remove Execute Permission for Scripts
        chmod -x ./.scripts/check/all_tag_version.sh
        chmod -x ./.scripts/check/latest_tag_version.sh
      shell: bash

    # - name: Add Execute Permission for Scripts
    #   run: chmod +x ${{ github.action_path }}/scripts/*.sh
    #   shell: bash

    # - name: Generate and Push New Tag
    #   run: ${{ github.action_path }}/scripts/create-tag.sh ${{ inputs.prefix }}
    #   shell: bash

    # - name: Register Environment Variables
    #   run: echo "NEW_VERSION=$(cat ./new_version.txt)" >> "$GITHUB_ENV"
    #   shell: bash

    # - name: Remove Execute Permission for Scripts
    #   run: chmod -x ${{ github.action_path }}/scripts/*.sh
    #   shell: bash
