name: "Create Tag"
description: "Create and push a new Git tag based on the highest version tag."

inputs:
  prefix:
    description: "Prefix for tag filtering"
    required: false
    default: "v"

outputs:
  new_version:
    description: "Generated Git tag"

runs:
  using: "composite"
  steps:
    - name: Add Execute Permission for Scripts
      run: chmod +x ${{ github.action_path }}/scripts/*.sh
      shell: bash

    - name: Generate and Push New Tag
      id: create_tag
      run: ${{ github.action_path }}/scripts/create-tag.sh ${{ inputs.prefix }}
      shell: bash

    - name: test
      run: |
        echo $(cat ./new_version.txt)
        echo "new_version=$(cat ./new_version.txt)" >> "$GITHUB_OUTPUT"
        cat "$GITHUB_OUTPUT"
      shell: bash

    - name: Remove Execute Permission for Scripts
      run: chmod -x ${{ github.action_path }}/scripts/*.sh
      shell: bash
