name: CI/CD Workflow

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  statuses: write

jobs:
  ci:
    name: CI Process (Git Info, Build, Test, Tagging, Release)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Git 정보 생성
      - name: Git Info
        run: |
          echo "Extracting Git Info..."
          ref=${{ github.ref }}
          if [[ "$ref" == refs/heads/* ]]; then
            branch_name=${ref#refs/heads/}
            tag_name="N/A"
          elif [[ "$ref" == refs/tags/* ]]; then
            branch_name="N/A"
            tag_name=${ref#refs/tags/}
          else
            echo "Unknown ref type: $ref"
            exit 1
          fi

      # Step 3: .NET 환경 설정
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SimpleFileIO.sln --no-cache

      # Step 4: 빌드 및 테스트
      - name: Build Debug DLL
        run: dotnet build SimpleFileIO/SimpleFileIO.csproj --configuration Debug --no-restore --output ./build/debug

      - name: Build Release DLL
        run: dotnet build SimpleFileIO/SimpleFileIO.csproj --configuration Release --no-restore --output ./build/release

      # Step 5: 자동 태그 생성
      - name: Get Latest Tag and Create New Tag
        id: create_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          if [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            new_tag="v$major.$minor.$((patch + 1))"
          else
            new_tag="v0.0.1"
          fi
          echo "::set-output name=new_tag::$new_tag"
          git tag $new_tag
          git push origin $new_tag

      # Step 6: 릴리스 생성
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: |
            ## What's New
            - Automated Release with Debug and Release builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: 릴리스 파일 업로드
      - name: Upload Debug Build
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/debug_build.zip
          asset_name: debug_build.zip
          asset_content_type: application/zip

      - name: Upload Release Build
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/release_build.zip
          asset_name: release_build.zip
          asset_content_type: application/zip
