name: Create Release on Tag with Build Artifacts

on:
  push:
    tags:
      - 'v*' # 태그 이름이 v로 시작하는 경우에만 실행

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Debug
        run: dotnet build SimpleFileIO/SimpleFileIO.csproj --configuration Debug --output ./build/debug

      - name: Build Release
        run: dotnet build SimpleFileIO/SimpleFileIO.csproj --configuration Release --output ./build/release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # 생성된 태그 이름
          release_name: Release ${{ github.ref_name }} # 릴리즈 이름
          body: |
            ## What's New
            This release includes the following build artifacts:
            - Debug Build
            - Release Build
            - Tag: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Debug Build
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/debug
          asset_name: debug_build.zip
          asset_content_type: application/zip

      - name: Upload Release Build
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/release
          asset_name: release_build.zip
          asset_content_type: application/zip
