name: Create Release on Tag with Builds

on:
  push:
    tags:
      - 'v*' # 태그 이름이 v로 시작하는 경우에만 실행
    branches:
      - 'main

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
      # 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # .NET 환경 설정
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 복원 단계
      - name: Restore dependencies
        run: dotnet restore SimpleFileIO/SimpleFileIO.csproj --no-cache

      # 디버그 빌드
      - name: Build Debug
        run: dotnet build SimpleFileIO/SimpleFileIO.csproj --configuration Debug --no-restore --output ./build/debug

      # 릴리즈 빌드
      - name: Build Release
        run: dotnet build SimpleFileIO/SimpleFileIO.csproj --configuration Release --no-restore --output ./build/release

      # 릴리즈 생성
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # 생성된 태그 이름
          release_name: Release ${{ github.ref_name }}  # 릴리즈 이름
          body: |
            ## What's New
            This release includes the following build artifacts:
            - Debug Build
            - Release Build
          draft: false  # 초안으로 생성하려면 true로 설정
          prerelease: false  # 프리릴리즈로 생성하려면 true로 설정

      # 디버그 빌드 결과 업로드
      - name: Upload Debug Build
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/debug
          asset_name: debug_build.zip
          asset_content_type: application/zip

      # 릴리즈 빌드 결과 업로드
      - name: Upload Release Build
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/release
          asset_name: release_build.zip
          asset_content_type: application/zip
