name: Main Branch Tag Management

on:
  workflow_run:
    workflows:
      - Continuous Integration (CI)
    types:
      - completed

permissions:
  contents: write
  statuses: read

jobs:
  create-main-tag:
    name: Create Tag
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'Main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Latest Tag and Create New Tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"

          if [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            
            new_patch=$((patch + 1))
            new_tag="v$major.$minor.$new_patch"
          else
            echo "No valid version tag found. Defaulting to v0.0.1."
            new_tag="v0.0.1"
          fi

          echo "New tag: $new_tag"

          git tag $new_tag
          git push origin $new_tag
