name: Main Push CI/CD

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  statuses: write

jobs:

  info-and-check:
    name: Info And Check
    runs-on: ubuntu-latest
    outputs:
      solution_project_value_result: ${{ steps.info-and-check.outputs.solution_project_value_result }}
      git_value_result: ${{ steps.info-and-check.outputs.git_value_result }}
      else_value_result: ${{ steps.info-and-check.outputs.else_value_result }}
      exist_files_result: ${{ steps.info-and-check.outputs.exist_files_result }}
      git_info_result: ${{ steps.info-and-check.outputs.git_info_result }}
    steps:
      - uses: actions/checkout@v4
      - name: Info And Check
        id: info-and-check
        uses: ./.github/actions/info
        with:
          # solution & project
          solution_file_path: "${{ vars.SOLUTION_FILE_PATH }}"
          dll_project_file_path: "${{ vars.DLL_PROJECT_FILE_PATH }}"
          tester_project_file_path: "${{ vars.TESTER_PROJECT_FILE_PATH }}"
          tester_executable_file_name: "${{ vars.TESTER_EXECUTABLE_FILE_NAME }}"
          # git
          git_event_name: "${{ github.event_name }}"
          git_ref: "${{ github.ref }}"
          head_ref: "${{ github.head_ref }}"
          base_ref: "${{ github.base_ref }}"
          # else
          result_zip_name: "${{ vars.RESULT_ZIP_NAME }}"
          tag_prefix: "${{ vars.TAG_PREFIX }}"
      
      - name: Check Output
        run: |
          # Check Output
          echo -e "\033[48;5;241m\033[38;5;15mResult\033[0m"
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
          printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Solution Project Value"
          echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
          echo -e "${{ steps.info-and-check.outputs.solution_project_value_result }}" || echo "::Warning::⚠️ Invalid Solution And Project Value Result"
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
          printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Git Value"
          echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
          echo -e "${{ steps.info-and-check.outputs.git_value_result }}" || echo "::Warning::⚠️ Invalid Git Value Result"
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
          printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Else Value"
          echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
          echo -e "${{ steps.info-and-check.outputs.else_value_result }}" || echo "::Warning::⚠️ Invalid Else Value Result"
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
          printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Exist Files"
          echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
          echo -e "${{ steps.info-and-check.outputs.exist_files_result }}" || echo "::Warning::⚠️ Invalid Exist Files Result"
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
          printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Git Info"
          echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
          echo -e "${{ steps.info-and-check.outputs.git_info_result }}" || echo "::Warning::⚠️ Invalid Git Info Result"

  build-validation:
    name: Build Validation
    needs: info-and-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
      - name: Dll Build Test
        id: dll-build-test
        uses: ./.github/actions/build-validation/dotnet
        with:
          project_file_path: "${{vars.DLL_PROJECT_FILE_PATH}}"
          build_configuration: "${{matrix.configuration}}"
          dotnet_version: "${{ vars.DOTNET_VERSION }}"
      - name: Check Output
        run: |
          # Check Output
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
          printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Build Validation"
          echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
          echo "${{ steps.dll-build-test.outputs.result }}" || echo "::Warning::⚠️ Invalid Build Validation Result"
        shell: bash

      - name: To File Output
        run: |
          # To File Output
          echo "${{ steps.dll-build-test.outputs.result }}" || echo "::Warning::⚠️ Invalid Build Validation Result" > ./${{ runner.os }}/${{ matrix.configuration }}/build_validation.result

      - uses: actions/upload-artifact@v4
        with:
            name: Build_Validation_${{ runner.os }}_${{ matrix.configuration }}
            path: ./${{ runner.os }}/${{ matrix.configuration }}/build_validation.result
            if-no-files-found: warn
            
  #create-tag:
  #  name: Create Tag
  #  needs: check-event
  #  runs-on: ubuntu-latest
  #  concurrency:
  #    group: tag-creation
  #    cancel-in-progress: false
  #  env:
  #    NEW_VERSION: ""
  #  outputs:
  #    new_version: ${{ env.NEW_VERSION }}
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        fetch-depth: 0

  #    - name: Before Check Tags
  #      uses: ./.github/actions/tag/version/check
  #      with:
  #        prefix: ${{ vars.TAG_PREFIX }}

  #    - name: Version Create Tag
  #      uses: ./.github/actions/tag/version/create
  #      with:
  #        prefix: ${{ vars.TAG_PREFIX }}

  #    - name: After Check Tags
  #      uses: ./.github/actions/tag/version/check
  #      with:
  #        prefix: ${{ vars.TAG_PREFIX }}

  results:
    name: Results
    needs: [info-and-check, build-validation]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
            name: Build_Validation_Linux_Debug
            path: ./results/build_validation/linux/debug
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
            name: Build_Validation_Linux_Release
            path: ./results/build_validation/linux/release
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
            name: Build_Validation_Windows_Debug
            path: ./results/build_validation/windows/debug
        continue-on-error: true
      - uses: actions/download-artifact@v4
        with:
            name: Build_Validation_Windows_Release
            path: ./results/build_validation/windows/release
        continue-on-error: true

      - name: Make Info Result Files
        run: |
          # Make Info Result Files

          # Set directory
          if [ ! -d "./results/info/" ]; then
              mkdir -p "./results/info/"
          fi

          # Git Info
          echo -e ${{ needs.info-and-check.outputs.git_info_result }} > ./results/info/git_info.result

          # Exist Files
          echo -e ${{ needs.info-and-check.outputs.exist_files_result }} > ./results/info/exist_files.result

          # Values
          temp_file=$(mktemp)
          echo -e "\033[38;5;245m● Solution & Project\033[0m" >> "$temp_file"
          if [[ -z "${{ needs.info-and-check.outputs.solution_project_value_result }}" ]]; then
            echo -e "\033[38;5;245m⚠️ Empty Solution And Project Value Result\033[0m" >> "$temp_file"
          else
            echo "${{ needs.info-and-check.outputs.solution_project_value_result }}" | awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' >> "$temp_file"
          fi
          echo -e "\033[38;5;245m● Git\033[0m" >> "$temp_file"
          if [[ -z "${{ needs.info-and-check.outputs.git_value_result }}" ]]; then
            echo -e "\033[38;5;245m⚠️ Empty Git Value Result\033[0m" >> "$temp_file"
          else
            echo "${{ needs.info-and-check.outputs.git_value_result }}" | awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' >> "$temp_file"
          fi
          echo -e "\033[38;5;245m● Else\033[0m" >> "$temp_file"
          if [[ -z "${{ needs.info-and-check.outputs.else_value_result }}" ]]; then
            echo -e "\033[38;5;245m⚠️ Empty Else Value Result\033[0m" >> "$temp_file"
          else
            echo "${{ needs.info-and-check.outputs.else_value_result }}" | awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' >> "$temp_file"
          fi
          cp "${temp_file}" "./results/info/value.result"
          rm -f "$temp_file"
        continue-on-error: true

      - name: Sermary
        run: echo Sermary

      - name: Info
        uses: ./.github/actions/results
        with:
          headers_and_files: >
            [
              {
                "header": "Git Info",
                "path": "./results/info/git_info.result"
              },
              {
                "header": "File Exist",
                "path": "./results/info/exist_files.result"
              },
              {
                "header": "Values",
                "path": "./results/info/value.result"
              }
            ]
          result_file: ./results/info_marge.result
          result_to_console: false
        continue-on-error: true

      - name: Build Validation
        uses: ./.github/actions/results
        with:
          headers_and_files: >
            [
              {
                "header": "Build Validation Linux Debug",
                "path": "./results/build_validation/linux/debug/build_validation.result"
              },
              {
                "header": "Build Validation Linux Release",
                "path": "./results/build_validation/linux/release/build_validation.result"
              },
              {
                "header": "Build Validation Widnows Debug",
                "path": "./results/build_validation/windows/debug/build_validation.result"
              },
              {
                "header": "Build Validation Widnows Release",
                "path": "./results/build_validation/windows/release/build_validation.result"
              }
            ]
          result_file: ./results/build_validation_marge.result
          result_to_console: false
        continue-on-error: true
      - name: Result
        run: |
          echo ${{ needs.info-and-check.result }}
          echo ${{ needs.build-validation.result }}
          cat ./results/info_marge.result
          cat ./results/build_validation_marge.result
        continue-on-error: true

  # check-event:
  #   name: Check Git Event
  #   needs: [windows-debug-ci, windows-release-ci, linux-debug-ci, linux-release-ci]
  #   # needs: [linux-debug-ci, linux-release-ci]
  #   runs-on: ubuntu-latest
  #   if: ${{github.event_name == 'push'}}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Is Push Event
  #       run: echo -e "\033[32mPush Ok...\033[0m Continue to Create Tag..."

  # create-tag:
  #   name: Create Tag
  #   needs: check-event
  #   runs-on: ubuntu-latest
  #   concurrency:
  #     group: tag-creation
  #     cancel-in-progress: false
  #   env:
  #     NEW_VERSION: ""
  #   outputs:
  #     new_version: ${{ env.NEW_VERSION }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Before Check Tags
  #       uses: ./.github/actions/tag/version/check
  #       with:
  #         prefix: ${{ vars.TAG_PREFIX }}

  #     - name: Version Create Tag
  #       uses: ./.github/actions/tag/version/create
  #       with:
  #         prefix: ${{ vars.TAG_PREFIX }}

  #     - name: After Check Tags
  #       uses: ./.github/actions/tag/version/check
  #       with:
  #         prefix: ${{ vars.TAG_PREFIX }}

  # cd:
  #   name: CD
  #   needs: [create-tag]
  #   runs-on: ubuntu-latest
  #   env:
  #     NEW_VERSION: ${{ needs.create-tag.outputs.new_version }}
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:

  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Show Current Tag
  #       run: |
  #         echo "Current VERSION: ${{ vars.TAG_PREFIX }}${{ env.NEW_VERSION }}"

  #     - name: Build Debug
  #       uses: ./.github/actions/build/linux/dotnet/dll
  #       with:
  #         solution_file_path: ${{ vars.SOLUTION_FILE_PATH }}
  #         dll_project_file_path: ${{ vars.DLL_PROJECT_FILE_PATH }}
  #         build_directory_path: ${{ vars.BUILD_DIRECTORY_PATH }}
  #         configuration: "Debug"
  #         dotnet_version: ${{ vars.DOTNET_VERSION }}
  #         assembly_version: ${{ vars.NEW_VERSION }}
  #         file_version: ${{ vars.NEW_VERSION }}
  #         informational_version: ${{ vars.NEW_VERSION }}

  #     - name: Build Release
  #       uses: ./.github/actions/build/linux/dotnet/dll
  #       with:
  #         solution_file_path: ${{ vars.SOLUTION_FILE_PATH }}
  #         dll_project_file_path: ${{ vars.DLL_PROJECT_FILE_PATH }}
  #         build_directory_path: ${{ vars.BUILD_DIRECTORY_PATH }}
  #         configuration: "Release"
  #         dotnet_version: ${{ vars.DOTNET_VERSION }}
  #         assembly_version: ${{ env.NEW_VERSION }}
  #         file_version: ${{ env.NEW_VERSION }}
  #         informational_version: ${{ env.NEW_VERSION }}

  #     - name: Zip Build File
  #       uses: ./.github/actions/deploy/build-result-as-zip
  #       with:
  #         build_directory_path: ${{ vars.BUILD_DIRECTORY_PATH }}
  #         result_zip_name: ${{ vars.RESULT_ZIP_NAME }}

  #     - name: Generate Changelog
  #       id: generate_changelog
  #       run: |
  #         git fetch --all
      
  #         base_ref=${{ github.base_ref }}
  #         head_sha=${{ github.sha }}
      
  #         if [ -z "$base_ref" ]; then
  #           # If base_ref is not provided, fallback to the previous commit
  #           base_ref=$(git rev-parse HEAD^)
  #         fi
      
  #         # Generate the changelog with commit title, hyperlinked hash, and body
  #         changelog=$(git log $base_ref..$head_sha --pretty=format:"%s [#%h](https://github.com/${{ github.repository }}/commit/%H)%n------------------------%n%b" --no-merges)
      
  #         if [ -z "$changelog" ]; then
  #           echo "No changes to log."
  #           changelog="No changes available for this release."
  #         fi
      
  #         echo "CHANGELOG<<EOF" >> $GITHUB_ENV
  #         echo "$changelog" >> $GITHUB_ENV
  #         echo "EOF" >> $GITHUB_ENV
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  #     - name: Create GitHub Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: ${{ vars.TAG_PREFIX }}${{ env.NEW_VERSION }}
  #         name: Release ${{ vars.TAG_PREFIX }}${{ env.NEW_VERSION }}
  #         body: ${{ env.CHANGELOG }}
  #         files: ${{ vars.BUILD_DIRECTORY_PATH }}/${{ vars.RESULT_ZIP_NAME }}.zip
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CHANGELOG: ${{ env.CHANGELOG }}