name: Main Branch Tag Management

on:
  workflow_run:
    branches:
      - 'main'
    workflows:
      - Main CI (Continuous Integration)
    types:
      - completed

      
permissions:
  contents: write
  statuses: read

jobs:
  create-main-tag:
    name: Create Main Tag
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref_name == 'main' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag and Create New Tag
        run: |
          echo "Fetching the latest tag..."

          # Get the latest tag or default to v0.0.0
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"

          # Extract version and increment
          if [[ "$latest_tag" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}

            # Increment
