name: Main Push CI/CD

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  statuses: write

jobs:

  info-and-check:
    name: Info And Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Info And Check
        uses: ./.github/actions/info
        with:
          # solution & project
          solution_file_path: "${{ vars.SOLUTION_FILE_PATH }}"
          dll_project_file_path: "${{ vars.DLL_PROJECT_FILE_PATH }}"
          build_directory_path: "${{ vars.BUILD_DIRECTORY_PATH }}"
          tester_project_file_path: "${{ vars.TESTER_PROJECT_FILE_PATH }}"
          tester_executable_file_name: "${{ vars.TESTER_EXECUTABLE_FILE_NAME }}"
          # deploy
          result_zip_name: "${{ vars.RESULT_ZIP_NAME }}"
          tag_prefix: "${{ vars.TAG_PREFIX }}"
          # git
          git_event_name: "${{ github.event_name }}"
          git_ref: "${{ github.ref }}"
          head_ref: "${{ github.head_ref }}"
          base_ref: "${{ github.base_ref }}"

      - uses: actions/upload-artifact@v4
        with:
          name: Info
          path: |
            ./git-info.result
            ./exist-files.result
            ./solution-project_value.result
            ./deploy-value.result
            ./git-value.result

  build-validation:
    name: Build Validation
    needs: info-and-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [debug, release]
    steps:
      - uses: actions/checkout@v4
      - name: Dll Build Test
        uses: ./.github/actions/build-validation/dotnet
        with:
          project_file_path: "${{vars.DLL_PROJECT_FILE_PATH}}"
          build_configuration: "${{matrix.configuration}}"
          dotnet_version: "${{ vars.DOTNET_VERSION }}"

      - uses: actions/upload-artifact@v4
        with:
            name: Build_Validation_${{ runner.os }}_${{ matrix.configuration }}
            path: ./${{ runner.os }}-${{ matrix.configuration }}.result
  results:
    name: Results
    needs: build-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        with:
            name: Info
            path: ./results/info
      - uses: actions/upload-artifact@v4
        with:
            name: Build_Validation_Linux_Debug
            path: ./results/build-validation/
      - uses: actions/upload-artifact@v4
        with:
            name: Build_Validation_Linux_Release
            path: ./results/build-validation/
      - uses: actions/upload-artifact@v4
        with:
            name: Build_Validation_Windows_Debug
            path: ./results/build-validation/
      - uses: actions/upload-artifact@v4
        with:
            name: Build_Validation_Windows_Release
            path: ./results/build-validation/



      - name: Info
        run: |
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────┐\033[0m\
                 \n\033[38;5;245m│  Git Info                                                │\033[0m\
                 \n\033[38;5;245m└──────────────────────────────────────────────────────────┘\033[0m"
          cat ./results/info/git-info.result
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────┐\033[0m\
                 \n\033[38;5;245m│  File Exist                                              │\033[0m\
                 \n\033[38;5;245m└──────────────────────────────────────────────────────────┘\033[0m"        
          cat ./results/info/exist-files.result
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────┐\033[0m\
                 \n\033[38;5;245m│  Values                                                  │\033[0m\
                 \n\033[38;5;245m└──────────────────────────────────────────────────────────┘\033[0m"
          echo -e "\033[38;5;245m● Solution & Project\033[0m"
          awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' ./results/info/solution-project-value.result
          echo -e "\033[38;5;245m● Deploy\033[0m"
          awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' ./results/info/deploy-value.result
          echo -e "\033[38;5;245m● Git\033[0m"
          awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' ./results/info/git-value.result
      - name: Build Validation
        run: |
          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────┐\033[0m\
                 \n\033[38;5;245m│  Build Validation Linux Debug                            │\033[0m\
                 \n\033[38;5;245m└──────────────────────────────────────────────────────────┘\033[0m"        
          cat ./results/build-validation//Linux-debug.result


  # check-event:
  #   name: Check Git Event
  #   needs: [windows-debug-ci, windows-release-ci, linux-debug-ci, linux-release-ci]
  #   # needs: [linux-debug-ci, linux-release-ci]
  #   runs-on: ubuntu-latest
  #   if: ${{github.event_name == 'push'}}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Is Push Event
  #       run: echo -e "\033[32mPush Ok...\033[0m Continue to Create Tag..."

  # create-tag:
  #   name: Create Tag
  #   needs: check-event
  #   runs-on: ubuntu-latest
  #   concurrency:
  #     group: tag-creation
  #     cancel-in-progress: false
  #   env:
  #     NEW_VERSION: ""
  #   outputs:
  #     new_version: ${{ env.NEW_VERSION }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Before Check Tags
  #       uses: ./.github/actions/tag/version/check
  #       with:
  #         prefix: ${{ vars.TAG_PREFIX }}

  #     - name: Version Create Tag
  #       uses: ./.github/actions/tag/version/create
  #       with:
  #         prefix: ${{ vars.TAG_PREFIX }}

  #     - name: After Check Tags
  #       uses: ./.github/actions/tag/version/check
  #       with:
  #         prefix: ${{ vars.TAG_PREFIX }}

  # cd:
  #   name: CD
  #   needs: [create-tag]
  #   runs-on: ubuntu-latest
  #   env:
  #     NEW_VERSION: ${{ needs.create-tag.outputs.new_version }}
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:

  #     - name: Checkout Repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Show Current Tag
  #       run: |
  #         echo "Current VERSION: ${{ vars.TAG_PREFIX }}${{ env.NEW_VERSION }}"

  #     - name: Build Debug
  #       uses: ./.github/actions/build/linux/dotnet/dll
  #       with:
  #         solution_file_path: ${{ vars.SOLUTION_FILE_PATH }}
  #         dll_project_file_path: ${{ vars.DLL_PROJECT_FILE_PATH }}
  #         build_directory_path: ${{ vars.BUILD_DIRECTORY_PATH }}
  #         configuration: "Debug"
  #         dotnet_version: ${{ vars.DOTNET_VERSION }}
  #         assembly_version: ${{ vars.NEW_VERSION }}
  #         file_version: ${{ vars.NEW_VERSION }}
  #         informational_version: ${{ vars.NEW_VERSION }}

  #     - name: Build Release
  #       uses: ./.github/actions/build/linux/dotnet/dll
  #       with:
  #         solution_file_path: ${{ vars.SOLUTION_FILE_PATH }}
  #         dll_project_file_path: ${{ vars.DLL_PROJECT_FILE_PATH }}
  #         build_directory_path: ${{ vars.BUILD_DIRECTORY_PATH }}
  #         configuration: "Release"
  #         dotnet_version: ${{ vars.DOTNET_VERSION }}
  #         assembly_version: ${{ env.NEW_VERSION }}
  #         file_version: ${{ env.NEW_VERSION }}
  #         informational_version: ${{ env.NEW_VERSION }}

  #     - name: Zip Build File
  #       uses: ./.github/actions/deploy/build-result-as-zip
  #       with:
  #         build_directory_path: ${{ vars.BUILD_DIRECTORY_PATH }}
  #         result_zip_name: ${{ vars.RESULT_ZIP_NAME }}

  #     - name: Generate Changelog
  #       id: generate_changelog
  #       run: |
  #         git fetch --all
      
  #         base_ref=${{ github.base_ref }}
  #         head_sha=${{ github.sha }}
      
  #         if [ -z "$base_ref" ]; then
  #           # If base_ref is not provided, fallback to the previous commit
  #           base_ref=$(git rev-parse HEAD^)
  #         fi
      
  #         # Generate the changelog with commit title, hyperlinked hash, and body
  #         changelog=$(git log $base_ref..$head_sha --pretty=format:"%s [#%h](https://github.com/${{ github.repository }}/commit/%H)%n------------------------%n%b" --no-merges)
      
  #         if [ -z "$changelog" ]; then
  #           echo "No changes to log."
  #           changelog="No changes available for this release."
  #         fi
      
  #         echo "CHANGELOG<<EOF" >> $GITHUB_ENV
  #         echo "$changelog" >> $GITHUB_ENV
  #         echo "EOF" >> $GITHUB_ENV
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  #     - name: Create GitHub Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: ${{ vars.TAG_PREFIX }}${{ env.NEW_VERSION }}
  #         name: Release ${{ vars.TAG_PREFIX }}${{ env.NEW_VERSION }}
  #         body: ${{ env.CHANGELOG }}
  #         files: ${{ vars.BUILD_DIRECTORY_PATH }}/${{ vars.RESULT_ZIP_NAME }}.zip
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CHANGELOG: ${{ env.CHANGELOG }}