name: Simple File I/O Library - CD

on:
  workflow_run:
    workflows: ["Simple File I/O Library - CI"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: List Available Artifacts
      run: |
        echo "Checking for available artifacts in the current workspace:"
        ls -la # 현재 디렉토리 확인

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: BuildOutput-${{ matrix.configuration }}

    - name: Verify Downloaded Artifacts
      run: |
        if [ -d "./output/${{ matrix.configuration }}" ]; then
          echo "Output folder exists for configuration: ${{ matrix.configuration }}"
          ls -la ./output/${{ matrix.configuration }}
        else
          echo "Output folder does not exist for configuration: ${{ matrix.configuration }}"
          exit 1
        fi

    - name: Deploy to Server
      run: |
        echo "Deploying to server for configuration: ${{ matrix.configuration }}..."
        scp ./output/${{ matrix.configuration }}/SimpleFileIO.dll user@your-server:/path/to/deployment/${{ matrix.configuration }}
        ssh user@your-server "sudo systemctl restart simplefileio-service-${{ matrix.configuration }}"
