name: Simple File I/O Library - CD

on:
  workflow_run:
    workflows: ["Simple File I/O Library - CI"]
    types:
      - completed

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: 1. Download artifact
      uses: actions/download-artifact@v3
      with:
        name: SimpleFileIO-DLL

    - name: 2. Deploy to server
      run: |
        echo "Deploying to server..."
        scp ./output/SimpleFileIO.dll user@your-server:/path/to/deployment/  # 서버로 복사
        ssh user@your-server "sudo systemctl restart simplefileio-service"  # 서비스 재시작
