name: Simple File I/O Library Main - CD

on:
  workflow_run:
    workflows: ["Simple File I/O Library Main - CI"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Debug GitHub Context
      run: |
        echo "Dumping GitHub Context:"
        echo ${{ toJson(github) }}

    - name: List Artifacts from Triggering Workflow
      run: |
        echo "Listing artifacts from the triggering workflow:"
        curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: BuildOutput-${{ matrix.configuration }}
        path: ./output/${{ matrix.configuration }}

    - name: Verify Downloaded Artifacts
      run: |
        if [ -d "./output/${{ matrix.configuration }}" ]; then
          echo "Output folder exists for configuration: ${{ matrix.configuration }}"
          ls -la ./output/${{ matrix.configuration }}
        else:
          echo "Output folder does not exist for configuration: ${{ matrix.configuration }}"
          exit 1
        fi

    - name: Deploy to Server
      run: |
        echo "Deploying to server for configuration: ${{ matrix.configuration }}..."
        scp ./output/${{ matrix.configuration }}/SimpleFileIO.dll user@your-server:/path/to/deployment/${{ matrix.configuration }}
        ssh user@your-server "sudo systemctl restart simplefileio-service-${{ matrix.configuration }}"
