name: Simple File I/O Library - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  

    env:
      Solution_Name: SimpleFileIO.sln
      Test_Project_Path: SimpleFileIO_Tester/SimpleFileIO_Tester.csproj
      Library_Project_Path: SimpleFileIO/SimpleFileIO.csproj

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore Dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build Library Project
      run: dotnet build ${{ env.Library_Project_Path }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Run Tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }} --no-restore --verbosity normal

    - name: Publish Artifacts
      run: dotnet publish ${{ env.Library_Project_Path }} --configuration ${{ matrix.configuration }} --output ./output

    - name: Check Output Folder
      run: |
        if (Test-Path ./output) {
          Write-Host "Output folder exists."
          Get-ChildItem -Force ./output
        } else {
          Write-Error "Output folder does not exist!"
        }

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BuildOutput
        path: ./output
