name: Simple File I/O Library - CD

on:
  workflow_run:
    workflows: ["Simple File I/O Library - CI"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Verify Downloaded Artifacts
      run: |
        echo "Checking downloaded artifacts..."
        ls -la ./output
    
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: BuildOutput

    - name: Verify Downloaded Artifacts
      run: |
        if [ -d "./output" ]; then
          echo "Output folder exists."
          ls -la ./output
        else
          echo "Output folder does not exist."
          exit 1
        fi

    - name: Deploy to Server
      run: |
        echo "Deploying to server..."
        scp ./output/SimpleFileIO.dll user@your-server:/path/to/deployment/
        ssh user@your-server "sudo systemctl restart simplefileio-service"
