name: Simple File I/O Library Main Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SimpleFileIO.sln

    - name: Extract version from csproj
      id: extract_version
      run: |
        version=$(cat SimpleFileIO/SimpleFileIO.csproj | grep '<Version>' | sed -E 's/.*<Version>(.*)<\/Version>.*/\1/')
        if [ -z "$version" ]; then
          echo "Project version not found in csproj file."
          exit 1
        fi
        echo "Project version is $version"
        echo "version=$version" >> $GITHUB_ENV

    - name: Build Debug configuration
      run: dotnet build SimpleFileIO/SimpleFileIO.csproj --configuration Debug --no-restore

    - name: Publish Debug DLL
      run: dotnet publish SimpleFileIO/SimpleFileIO.csproj --configuration Debug --output ./output/Debug

    - name: Verify Debug Output Folder
      run: |
        if [ ! -f "./output/Debug/SimpleFileIO.dll" ]; then
          echo "Debug DLL not found."
          exit 1
        fi

    - name: Build Release configuration
      run: dotnet build SimpleFileIO/SimpleFileIO.csproj --configuration Release --no-restore

    - name: Publish Release DLL
      run: dotnet publish SimpleFileIO/SimpleFileIO.csproj --configuration Release --output ./output/Release

    - name: Verify Release Output Folder
      run: |
        if [ ! -f "./output/Release/SimpleFileIO.dll" ]; then
          echo "Release DLL not found."
          exit 1
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.version }}
        release_name: "v${{ env.version }}"
        draft: false
        prerelease: false

    # Debug DLL Upload
    - name: Upload Debug DLL to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/Debug/SimpleFileIO.dll
        asset_name: SimpleFileIO-Debug.dll
        asset_content_type: application/octet-stream

    # Release DLL Upload
    - name: Upload Release DLL to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/Release/SimpleFileIO.dll
        asset_name: SimpleFileIO-Release.dll
        asset_content_type: application/octet-stream
